services:
  - type: web
    name: rundj-server
    env: go
    region: ohio
    plan: starter
    buildCommand: |
      go mod download
      go build -o server
    startCommand: ./server
    envVars:
      - key: PORT
        value: 8080
    scaling:
      minInstances: 1
      maxInstances: 3