services:
  - type: web
    name: go-server
    env: go
    region: ohio
    plan: starter
    buildCommand: go build -o main
    startCommand: ./main
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 8080
    autoDeploy: true
    scaling:
      minInstances: 1
      maxInstances: 3
      targetMemoryPercent: 60
      targetCPUPercent: 60